---
title: "Make UGA dashboard"
output:
  rmdformats::html_clean
---

```{r, include=FALSE}
library(dashdash)
library(readstata13)
library(readxl)
library(labelled)
```


# Gather inputs

```{r}

my_vars <- read_excel("C:/Users/solis/Dropbox/WZB/KCCA_C19_dashboard/my_vars2.xlsx") 

vars_used  <- my_vars %>% filter(!is.na(variable)) %>% pull(variable)
vars_used  <- c("date", vars_used)

my_data <- haven::read_stata("C:/Users/solis/Dropbox/WZB/KCCA_C19_dashboard/data/r1r2_editted_merged_0801.dta") %>%
  rename(date=today) %>%
  mutate(id="Kampala")

# Checks
if(!all(vars_used %in% names(my_data))){
  print(paste("Missing variables:", 
              paste(vars_used[!(vars_used %in% names(my_data))], collapse = ", ")))
  vars_used <- vars_used[(vars_used %in% names(my_data))]
  }

# Light data cleaning
my_data <- select(my_data, c("id", all_of(vars_used)))  %>%
  mutate(date = as.Date(date)) %>%
  filter(date >= as.Date("2020-04-30"))

my_vars <- my_vars %>% filter(variable %in% vars_used) 

my_args <- read_excel("C:/Users/solis/Dropbox/WZB/KCCA_C19_dashboard/my_args.xlsx")



```

```{r, message = FALSE, warning = FALSE, include = FALSE}
wd <- getwd()
dashdash::dashdash(
  output_file = paste0(wd, "/surveys/r1.html"),
  my_data = my_data,
  my_vars = my_vars,
  my_args = my_args)

```


<embed type="text/html" src="surveys/r1.html" width="800" height="800">


